---


- name: "install packages"
  become : true
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx


- name: Disable the default site
  file:
    path: "{{nginx_conf_dir}}/sites-enabled/default"
    state: absent
  notify:
    - reload nginx

- name: Create the configurations
  template:
    src: "mopidy.j2"
    dest: "{{ nginx_conf_dir }}/sites-available/mopidy.conf"
  notify:
    - reload nginx

- name: Create links for sites-enabled
  file:
    state: link
    src: "{{ nginx_conf_dir }}/sites-available/mopidy.conf"
    dest: "{{ nginx_conf_dir }}/sites-enabled/mopidy.conf"
  notify:
    - reload nginx
