---

- name: "download client"
  get_url:
      url: "{{ url }}/v{{ version }}/snapserveyr_{{ version }}_{{ server_arch }}.deb"
      dest: /tmp/snapclient_{{ version }}_armhf.deb

- name: Install a .deb package
  apt:
    deb: /tmp/snapclient_{{ version }}_armhf.deb


- name: Install missing dependencies
  apt:
   upgrade: true

- name: "restart snapclient"
  service:
     name: snapclient
     state: restarted