---
# init tasks main

- name: "update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Upgrade packages"
  apt:
    upgrade: safe

- name: "Remove dependencies that are no longer required"
  apt:
    autoremove: yes


- name: "Install package"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - isc-dhcp-server
    - avahi-daemon
    - avahi-discover
    - libnss-mdns
